version: '3.3'

volumes:
  db-data:
  static:
  media:

services:

  db:
    image: postgres:13
    container_name: Postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backendiwe
    env_file: .env
    volumes:
      - static_2:/backend_static/
      - media_2:/app/media/
      - docs_2:/app/api/docs
    depends_on:
      - db
    # env_file:
    #   - ./.env

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_2:/static

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginxrabotaipojaluista
    ports:
      - 80:80
    volumes:
      - static:/staticfiles
      - media:/app/media/
