version: '3' 
 
volumes: 
  static_Prod: 
  media_Prod: 
  db_data_Prod: 
  docs_Prod: 

services: 
  db: 
    image: postgres:13 
    container_name: foodgram_Postgres 
    volumes: 
      - db_data_Prod:/var/lib/postgresql/data 
    env_file: 
      - ./.env 

  backend: 
    build: 
      context: ../backend 
      dockerfile: Dockerfile 
    env_file: 
      - ./.env 
    depends_on: 
      - db 
    container_name: foodgram_backend 
    volumes: 
      - static_Prod:/backend_static/ 
      - media_Prod:/app/media/ 
      - docs_Prod:/app/api/docs/ 
 
  frontend: 
    build: 
      context: ../frontend 
      dockerfile: Dockerfile 
    container_name: foodgram_frontend 
    command: cp -r /app/build/. /frontend_static/ 
    volumes: 
      - static_Prod:/frontend_static/ 
      - docs_Prod:/app/docs/ 

  nginx: 
    build: 
      context: ../nginx 
      dockerfile: Dockerfile 
    container_name: foodgram_gateway 
    ports: 
      - "8888:80" 
    volumes: 
      - docs_Prod:/usr/share/nginx/html/api/docs/ 
      - static_Prod:/staticfiles 
      - media_Prod:/app/media/ 
    depends_on: 
      - backend 
      - frontend 
