version: '3.3'

volumes:
  static_dev:
  media_dev:
  db_data_dev:
  docs_dev:

services:

  db:
    image: postgres:13
    container_name: Postgres_Dev
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend_Dev
    volumes:
      - static_dev:/app/result_build/build/
      - docs_dev:/app/docs/

  nginx:
    image: nginx:1.19.3
    container_name: nginx_Dev
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_dev:/usr/share/nginx/html/
      - docs_dev:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
