# Generated by Django 3.2.16 on 2024-03-27 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Ингредиентов должна быть не меньше 1.'), django.core.validators.MaxValueValidator(999999, message='Ингредиентов должна быть не более 999999.')], verbose_name='Количество'),
        ),
    ]
