# Generated by Django 3.2.16 on 2024-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourites',
            name='unique_users_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_user_recipes',
        ),
        migrations.AddConstraint(
            model_name='favourites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_favourites'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_shoppgng_list'),
        ),
    ]
