# Food

MAX = 100
UNIT_MAX_LENGTH = 30
NAME_MAX_LENGTH = 200
COLOR_CODE_MAX_LENGTH = 7
FIELD_MIN_AMOUNT = 1
FIELD_MAX_AMOUNT = 55


# Users

EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 150
